### PR TITLE
po: Update Spanish translation

### PR DESCRIPTION
**Pull request by oscfdezdz**

### CODE REVIEW

**Comment by oscfdezdz** [comment]
I've just seen 6027c28503b6d5301dbeb8f59d94f4f3302f20a7, this should probably wait till that one is on master to translate appdata changelog as well.

**Comment by mjakeman** [comment]
> I've just seen 6027c28, this should probably wait till that one is on master to translate appdata changelog as well.

Ah, good point. I wasn't thinking of the appdata file in terms of translations. I've merged it as part of #59, since I'm not quite ready for a release yet.

On the topic of testing, could you try run the latest master (should be a [prebuilt flatpak here](https://github.com/mjakeman/extension-manager/actions/runs/1738126705)) and tell me if the interface is properly localised for you? I'm having some trouble with locales not being recognised, and I definitely want to avoid shipping broken translations.

**Comment by mjakeman** [comment]
Removed the changelog commit and rebased on master. Let's merge this now

Thanks again!

**Comment by oscfdezdz** [comment]
> On the topic of testing, could you try run the latest master (should be a [prebuilt flatpak here](https://github.com/mjakeman/extension-manager/actions/runs/1738126705)) and tell me if the interface is properly localised for you? I'm having some trouble with locales not being recognised, and I definitely want to avoid shipping broken translations.

Only appdata seems to translate, without testing if so, I think `GETTEXT_PACKAGE` variable needs to be `app-id` when it's a Flatpak and `meson.project_name()` when it's not. Also using `GETTEXT_PACKAGE` in `po/meson.build`.

**Comment by mjakeman** [comment]
I tried changing the gettext package to use the `app-id` but that unfortunately did nothing. Interestingly, this seems to be a flatpak problem with mixed-locale systems.

Setting the language explicitly:
```
flatpak config --set languages 'en;es'
```
Then updating:
```
flatpak update
```
Was enough for me to use extension-manager (and other GTK 4-based programs) in Spanish or English, depending on the locale I had set. I'm not sure if there's anything we can do project-side to make this easier, but I think I will add some instructions to the readme and leave it at that for now.

**Comment by oscfdezdz** [comment]
> I tried changing the gettext package to use the `app-id` but that unfortunately did nothing. It shouldn't be a requirement, since a lot of gnome apps name their gettext package `gnome-*`.

My bad, I forgot about that.

Exporting the project in GNOME Builder or using the runtime variable `LANGUAGE` to test translations does work.

**Pull request merged**
