### PR TITLE
detail-view: Add info bar

### PR DESCRIPTION
**Pull request by oscfdezdz**
TODO:
- [x] Show latest version available for the installed GNOME Shell version
- [x] Drop supported versions (?)
- [x] Make it focusable for keyboard navigation and screen readers
- [x] Review implementation again

image

### CODE REVIEW

**Comment by oscfdezdz** [comment]
It's ready now, at least for review. I tried to make it easy to add more information in the future, since, for example, session modes are not available for now.

Also, I removed supported versions but I'm not sure if that was only in the case of using GNOME version instead of extension version.

As for layout, it's still an open question.

**Comment by oscfdezdz** [comment]
Actually, adding more elements would require changes for smaller screens. I've to figure out how to use AdwBreakPoint in `exm-window` here.

**Comment by oscfdezdz** [comment]
image

**Comment by mjakeman** [comment]
Really like the direction this is going in.

I think it's fine as-is if you can fix the merge conflicts, as it doesn't look as out of place with the new Homepage Extension tab.

For now let's hold off on merging. I'll tag a new release with a lot of your recent bug fixes and changes (v0.4.3) to fix the search issues people have been having. Then we can look at merging this plus some other broader changes to the design page for 0.5.

**Comment by oscfdezdz** [comment]
Merging conflicts are solved!

BTW `version_name` is a new field, it doesn't replace the existing `version` field.

**Review by mjakeman — APPROVED** [review]
Very clean implementation - this is awesome

I think the info-bar/info-bar-item pattern (defining properties in blueprint) is really nice. Will look to use this more across the UI when it gets a long overdue revisit.

**Comment by oscfdezdz** [comment]
Thanks! Since the rows in GTK/Libadwaita are only for vertical layouts and I didn't see another widget with a similar look and feel, a custom widget seemed the best option for this case.

**Pull request merged**
