### PR TITLE
metainfo: Add brand colors

### PR DESCRIPTION
**Pull request by oscfdezdz**
See https://docs.flathub.org/blog/introducing-app-brand-colors/

Taken from homepage https://mattjakeman.com/apps/extension-manager.html

| Light | Dark |
| -------- | ------- |
| image | image |

### CODE REVIEW

**Comment by mjakeman** [comment]
Nice!

I'm not too sure about the dark blue contrast-wise (which I did admittedly choose 😅)

I'll have a think and get back to you

**Comment by oscfdezdz** [comment]
This should make it easier to test: https://docs.flathub.org/banner-preview/

**Comment by oscfdezdz** [comment]
What about these?

imagen

**Comment by mjakeman** [comment]
Thoughts on #005edf? I think it's somewhere in the middle of those two

image

**Comment by oscfdezdz** [comment]
Let's go with those! It has better contrast and the edges of the icon are better outlined from the background.

**Pull request merged**
