### PR TITLE
Allow installing unsupported extensions

### LINKED ISSUE #64: Allow installing extensions on unsupported version if `/org/gnome/shell/disable-extension-version-validation` is set
First of all: great app, thanks a lot - and congrats for the new release!

I'm a Mutter developer and thus run a development version of Mutter/Gnome-Shell most of the cycle as my daily driver - essentially dogfooding myself all the new features to help ensuring stability. As extensions usually only declare versions supported once a stable version was released, I have to run with `/org/gnome/shell/disable-extension-version-validation` enabled.
I'd love to use your app to try extensions from time to time, thus I'd like to humbly request to allow that if the setting above is set - maybe with some kind of visual warning.

### PR DESCRIPTION
**Pull request by mjakeman**
- Rework install button
 - Unify install state between detail view and search rows
 - Warn the user if they try to install an unsupported extension

Unfortunately, it is impossible to access gnome shell's version check gsettings key from within the sandbox. For now, let all users install 'unsupported' extensions as the reworked error handling will list them as out of date anyway. If the user manually overrides the `disable-extension-version-validation` preference, then Extension Manager will reflect those changes.

Fixes #64

### CODE REVIEW

**Comment by dubreuia** [comment]
Hello @mjakeman , thank you for the great plugin it is amazing :pray: 

It seems I'm able to install unsupported extension, but I'm unable to enable them, is that the intended behavior? Do you know a way I can force the enable? I'm guessing they work even if wrong version

Screenshot from 2022-05-30 21-10-29

**Comment by mjakeman** [comment]
Hi @dubreuia, that is indeed intended. As out of date extensions can cause instability (and are *strongly* discouraged by upstream), they will not be loaded by default.

You can change this behaviour by toggling the `disable-extension-version-validation` setting, which is [described here](https://github.com/mjakeman/extension-manager#-using-unsupported-extensions) in the README. This will let you use outdated extensions, at your own risk of course.

Hope that helps :)

**Comment by dubreuia** [comment]
Thank you for getting back to me

> You can change this behaviour by toggling the disable-extension-version-validation setting, which is [described here](https://github.com/mjakeman/extension-manager#-using-unsupported-extensions) in the README. This will let you use outdated extensions, at your own risk of course.

That's what I did, but I still can't enable them. Is there anything else to do to be able to enable them?

**Comment by mjakeman** [comment]
What OS and Shell version are you using?

Can you provide the output of:
```
gsettings get org.gnome.shell disable-extension-version-validation
```

**Comment by dubreuia** [comment]
Ubuntu 22.04 LTS 64-bit / Gnome version: 42.1

```
gsettings get org.gnome.shell disable-extension-version-validation
```

**Comment by mjakeman** [comment]
Let's use #209 to track the issue. It might be an issue with GNOME Shell itself but we should look into it a bit first.

**Pull request merged**
