### PR TITLE
po: Add Catalan language

### PR DESCRIPTION
**Pull request by juxuanu**

### CODE REVIEW

**Comment by mjakeman** [comment]
Thank you!

Looks good to me, let's merge.

We've just added a new `translator-credits` string in master, so translators get proper credit in the about dialog. Could you open a new PR and add yourself to that too?

**Comment by juxuanu** [comment]
@mjakeman How do I generate the new .po file for Catalan?

**Comment by mjakeman** [comment]
@juxuanu I'm assuming you're using Poedit here?

First, check out the latest master branch with git (make sure the `translator-credits` string is available inside the POT file).

You can update the existing Catalan translation with the new strings from the menu by going `Translation->Update from POT File...` and selecting `extension-manager.pot`.

Then just need to fill out the `translator-credits` field. You'll want to have the format `Firstname Lastname` or `Firstname Lastname <email@website.com>` if you want to provide an email.

**Comment by juxuanu** [comment]
Ah, thanks, I thought I had to generate it with Meson.
Cheers!

**Pull request merged**
