### PR TITLE
Add screenshots for translation guide

### PR DESCRIPTION
**Pull request by Vovkiv**
Follow up to #514.
Adds screenshots to guide for: POEditor, GNOME Builder, Github.
Check here: https://github.com/Vovkiv/extension-manager/tree/screenshots-for-translation-guide/po
Also might change or additional steps due do screenshots.

Initially, I wanted to use webp images for smallest size possible, but since there chance that some browsers don't support webp, used png instead. I compressed them with Curtail and removed metadata.

### CODE REVIEW

**Review by mjakeman — APPROVED** [review]
Perfect. Thanks for putting this together.

Is this ready to merge?

**Comment by Vovkiv** [comment]
Not yet, only around ~25% or screenshots ready

**Review by oscfdezdz — APPROVED** [review]
Looks fantastic! Is it ready now?

**Comment by Vovkiv** [comment]
> Looks fantastic! Is it ready now?

I think yes

**Pull request merged**
