### PR TITLE
po: Update Polish translation

### PR DESCRIPTION
**Pull request by rafal06**

### CODE REVIEW

**Comment by mjakeman** [comment]
Thanks again!

Could you add yourself to the `translator-credits` string that's just been added in master?

**Comment by rafal06** [comment]
Just write my name there, right?

**Comment by mjakeman** [comment]
Yep. Optionally, you can also include an email if you'd like. Up to you

e.g. `Firstname Lastname <email@website.com>`

**Comment by rafal06** [comment]
Done

**Pull request merged**
